name: Tests
on:
  push:
    branches:
      - main
      - "v*"
    tags:
      - "v*"
  pull_request:

jobs:
  lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@2023.1.3

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Go Code
        run: staticcheck ./...

  test:
    name: Go Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go-version: [1.19.x, 1.21.x]
    env:
      GOPATH: ${{ github.workspace }}/go
      GOBIN: ${{ github.workspace }}/go/bin
      GOTEST_GITHUB_ACTIONS: 1
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/trisacrypto/courier
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Speedup
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: ${{ env.GOPATH }}/src/github.com/trisacrypto/courier

      - name: Run Unit Tests
        run: go test -v -coverprofile=coverage.txt -covermode=atomic --race ./...